/*
 * Copyright (c) 2025 Singular™
 * SPDX-License-Identifier: MIT
 */

package ai.singlr.helios.model.chat;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * A chat completion message generated by the model.
 **/

@JsonIgnoreProperties(ignoreUnknown = true)
public record ChatCompletionMessage(
    String content,
    String refusal,
    @JsonProperty("tool_calls")
    List<ChatCompletionMessageToolCall> toolCalls,
    ChatCompletionRole role
) {

  public static Builder newBuilder() {
    return new Builder();
  }

  public static Builder newBuilder(ChatCompletionMessage message) {
    return new Builder(message);
  }

  public static ChatCompletionMessage sys(String content) {
    return new Builder().withRole(ChatCompletionRole.SYSTEM).withContent(content).build();
  }

  public static ChatCompletionMessage user(String content) {
    return new Builder().withRole(ChatCompletionRole.USER).withContent(content).build();
  }

  public static class Builder {
    private String content;
    private String refusal;
    private List<ChatCompletionMessageToolCall> toolCalls;
    private ChatCompletionRole role;

    private Builder() {}

    private Builder(ChatCompletionMessage message) {
      this.content = message.content;
      this.refusal = message.refusal;
      this.toolCalls = message.toolCalls;
      this.role = message.role;
    }

    public Builder withContent(String content) {
      this.content = content;
      return this;
    }

    public Builder withRefusal(String refusal) {
      this.refusal = refusal;
      return this;
    }

    public Builder withToolCalls(List<ChatCompletionMessageToolCall> toolCalls) {
      this.toolCalls = toolCalls;
      return this;
    }

    public Builder withRole(ChatCompletionRole role) {
      this.role = role;
      return this;
    }

    public ChatCompletionMessage build() {
      return new ChatCompletionMessage(
          content,
          refusal,
          toolCalls,
          role
      );
    }
  }
}
